# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aac6e24d358829ffffd2f1b90afa3d625c91abb1c0031b504faa90dbf6cdcc7ceecc17a876be15bc92e5479b95dd96cf707339f29238f9db0682a0ce0b2f81e9

test:
  secret_key_base: 6b4177246159127076b3719f5b16c486e69f3f9e9ee7c486ac26d0e22f8e32f54eb60c777d7f88932707223f21b5a05fcf13d3dbf14f4186e2b42b5393ff3524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
